[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "0.8.6", features = ["csr", "nightly"] }
leptos_router = { version = "0.8.5" }
console_error_panic_hook = "0.1.7"
